environment:
  matrix:
  - nodejs_version: "lts"
  - nodejs_version: "stable"

install:
  - ps: Install-Product node stable
  - ps: Install-Product node lts
  - npm install

build_script:
  - npm run build

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - npm run coverage
